# Generated by Django 4.2.2 on 2023-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
