# Generated by Django 4.2.2 on 2023-06-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
